apiVersion: monitoring.coreos.com/v1
kind: PodMonitor 
metadata: 
  name: nginx-podmonitor 
  labels: 
    app: nginx 
spec:
  namespaceSelector: 
    matchNames: 
      - default 
  selector: 
    matchLabels: 
      app: nginx 
  podMetricsEndpoints: 
    - interval: 10s 
      path: /metrics 
      targetPort: 9113
