apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-nodeport 
  labels: 
    app: nginx     
spec: 
  selector: 
    app: nginx 
  ports: 
  - port: 80 
    protocol: TCP 
    name: http
    targetPort: 80 
    nodePort: 32000 
  type: NodePort
